# Root Netlify configuration for the entire project
[build]
  publish = "orchid-haven-showcase/dist"
  command = "cd orchid-haven-showcase && npm install && npm run build"

# Handle SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Specific redirects for admin and login pages
[[redirects]]
  from = "/admin"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/login"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/the-group"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/career"
  to = "/index.html"
  status = 200

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 404
